version: '3'
services:
  softplan_img:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: softplan_img/api
    ports:
      - 8080:8080
      - 5005:5005
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev